// ============================================================================
// Temu Smash Bros - Character Definitions
// ============================================================================

export interface HitboxData {
  offsetX: number;
  offsetY: number;
  width: number;
  height: number;
}

export interface MoveData {
  name: string;
  startup: number;
  active: number;
  endlag: number;
  damage: number;
  knockbackBase: number;
  knockbackGrowth: number;
  angle: number;
  hitboxes: HitboxData[];
}

export interface FighterData {
  id: string;
  name: string;
  title: string;
  weight: number;
  walkSpeed: number;
  runSpeed: number;
  jumpForce: number;
  doubleJumpForce: number;
  airSpeed: number;
  airAccel: number;
  fallSpeed: number;
  fastFallSpeed: number;
  gravity: number;
  shieldHealth: number;
  colors: { primary: string; secondary: string; accent: string; glow: string };
  size: { width: number; height: number };
  moves: Record<string, MoveData>;
}

// ============================================================================
// BLAZE - "The Infernal Brawler"
// Fire-themed bruiser. Strong ground game, powerful smash attacks, mediocre air
// game. Slow startup on power moves but devastating damage.
// ============================================================================
const blaze: FighterData = {
  id: 'blaze',
  name: 'BLAZE',
  title: 'The Infernal Brawler',
  weight: 105,
  walkSpeed: 0.85,
  runSpeed: 1.7,
  jumpForce: 15,
  doubleJumpForce: 13,
  airSpeed: 0.9,
  airAccel: 0.05,
  fallSpeed: 1.5,
  fastFallSpeed: 2.6,
  gravity: 0.1,
  shieldHealth: 50,
  colors: {
    primary: '#E85D04',
    secondary: '#DC2F02',
    accent: '#FFBA08',
    glow: '#FF6700',
  },
  size: { width: 44, height: 52 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 3,
      active: 2,
      endlag: 6,
      damage: 2.5,
      knockbackBase: 10,
      knockbackGrowth: 15,
      angle: 70,
      hitboxes: [{ offsetX: 20, offsetY: -4, width: 18, height: 14 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 3,
      active: 2,
      endlag: 7,
      damage: 2.5,
      knockbackBase: 12,
      knockbackGrowth: 15,
      angle: 60,
      hitboxes: [{ offsetX: 22, offsetY: -2, width: 18, height: 14 }],
    },
    jab3: {
      name: 'Flame Jab Finisher',
      startup: 5,
      active: 3,
      endlag: 12,
      damage: 5,
      knockbackBase: 40,
      knockbackGrowth: 30,
      angle: 40,
      hitboxes: [{ offsetX: 24, offsetY: -4, width: 24, height: 18 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Flame Swipe',
      startup: 7,
      active: 4,
      endlag: 14,
      damage: 9,
      knockbackBase: 25,
      knockbackGrowth: 55,
      angle: 35,
      hitboxes: [{ offsetX: 18, offsetY: -6, width: 28, height: 20 }],
    },
    up_tilt: {
      name: 'Rising Ember',
      startup: 6,
      active: 5,
      endlag: 12,
      damage: 8,
      knockbackBase: 20,
      knockbackGrowth: 60,
      angle: 85,
      hitboxes: [{ offsetX: 4, offsetY: -28, width: 26, height: 24 }],
    },
    down_tilt: {
      name: 'Low Burn',
      startup: 5,
      active: 3,
      endlag: 10,
      damage: 7,
      knockbackBase: 15,
      knockbackGrowth: 40,
      angle: 70,
      hitboxes: [{ offsetX: 16, offsetY: 10, width: 24, height: 12 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Inferno Fist',
      startup: 16,
      active: 4,
      endlag: 26,
      damage: 18,
      knockbackBase: 40,
      knockbackGrowth: 95,
      angle: 35,
      hitboxes: [
        { offsetX: 20, offsetY: -6, width: 32, height: 22 },
        { offsetX: 36, offsetY: -4, width: 18, height: 18 },
      ],
    },
    up_smash: {
      name: 'Flame Uppercut',
      startup: 12,
      active: 5,
      endlag: 24,
      damage: 16,
      knockbackBase: 35,
      knockbackGrowth: 90,
      angle: 88,
      hitboxes: [
        { offsetX: 0, offsetY: -24, width: 24, height: 28 },
        { offsetX: -6, offsetY: -36, width: 30, height: 16 },
      ],
    },
    down_smash: {
      name: 'Ground Flare',
      startup: 14,
      active: 6,
      endlag: 22,
      damage: 15,
      knockbackBase: 35,
      knockbackGrowth: 80,
      angle: 25,
      hitboxes: [
        { offsetX: -24, offsetY: 6, width: 26, height: 16 },
        { offsetX: 22, offsetY: 6, width: 26, height: 16 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Flame Spin',
      startup: 6,
      active: 4,
      endlag: 12,
      damage: 8,
      knockbackBase: 18,
      knockbackGrowth: 40,
      angle: 50,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 36, height: 36 }],
    },
    forward_air: {
      name: 'Fire Fist',
      startup: 9,
      active: 3,
      endlag: 16,
      damage: 11,
      knockbackBase: 20,
      knockbackGrowth: 60,
      angle: 40,
      hitboxes: [{ offsetX: 22, offsetY: -4, width: 22, height: 18 }],
    },
    back_air: {
      name: 'Flame Kick',
      startup: 8,
      active: 3,
      endlag: 14,
      damage: 14,
      knockbackBase: 30,
      knockbackGrowth: 85,
      angle: 145,
      hitboxes: [{ offsetX: -24, offsetY: -2, width: 22, height: 18 }],
    },
    up_air: {
      name: 'Fire Flip',
      startup: 7,
      active: 4,
      endlag: 14,
      damage: 9,
      knockbackBase: 18,
      knockbackGrowth: 55,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: -24, width: 28, height: 18 }],
    },
    down_air: {
      name: 'Meteor Stomp',
      startup: 14,
      active: 3,
      endlag: 20,
      damage: 13,
      knockbackBase: 25,
      knockbackGrowth: 70,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 18, width: 20, height: 20 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Flame Punch',
      startup: 12,
      active: 5,
      endlag: 18,
      damage: 14,
      knockbackBase: 30,
      knockbackGrowth: 70,
      angle: 30,
      hitboxes: [
        { offsetX: 14, offsetY: -4, width: 20, height: 18 },
        { offsetX: 30, offsetY: -2, width: 16, height: 16 },
      ],
    },
    side_special: {
      name: 'Eruption',
      startup: 18,
      active: 8,
      endlag: 28,
      damage: 16,
      knockbackBase: 45,
      knockbackGrowth: 80,
      angle: 80,
      hitboxes: [
        { offsetX: 24, offsetY: -10, width: 22, height: 40 },
        { offsetX: 24, offsetY: -30, width: 18, height: 20 },
      ],
    },
    up_special: {
      name: 'Rocket Boost',
      startup: 8,
      active: 12,
      endlag: 22,
      damage: 10,
      knockbackBase: 20,
      knockbackGrowth: 50,
      angle: 75,
      hitboxes: [{ offsetX: 0, offsetY: -16, width: 24, height: 30 }],
    },
    down_special: {
      name: 'Heat Shield',
      startup: 5,
      active: 16,
      endlag: 20,
      damage: 12,
      knockbackBase: 35,
      knockbackGrowth: 75,
      angle: 45,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 32, height: 32 }],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Grab',
      startup: 6,
      active: 2,
      endlag: 20,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 18, offsetY: -2, width: 16, height: 14 }],
    },
    pummel: {
      name: 'Fire Pummel',
      startup: 1,
      active: 1,
      endlag: 8,
      damage: 1.5,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 10, offsetY: 0, width: 10, height: 10 }],
    },
    forward_throw: {
      name: 'Blaze Toss',
      startup: 8,
      active: 2,
      endlag: 16,
      damage: 9,
      knockbackBase: 45,
      knockbackGrowth: 55,
      angle: 40,
      hitboxes: [{ offsetX: 16, offsetY: 0, width: 14, height: 14 }],
    },
    back_throw: {
      name: 'Backdraft',
      startup: 9,
      active: 2,
      endlag: 18,
      damage: 10,
      knockbackBase: 50,
      knockbackGrowth: 60,
      angle: 140,
      hitboxes: [{ offsetX: -16, offsetY: 0, width: 14, height: 14 }],
    },
    up_throw: {
      name: 'Magma Geyser',
      startup: 7,
      active: 2,
      endlag: 20,
      damage: 8,
      knockbackBase: 55,
      knockbackGrowth: 55,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -14, width: 14, height: 14 }],
    },
    down_throw: {
      name: 'Ember Slam',
      startup: 6,
      active: 2,
      endlag: 14,
      damage: 6,
      knockbackBase: 30,
      knockbackGrowth: 35,
      angle: 70,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 14, height: 14 }],
    },
  },
};

// ============================================================================
// ZEPHYR - "The Storm Dancer"
// Wind-themed speedster. Incredible speed and combo potential, poor kill power.
// Fast moves with low endlag, strings together combos.
// ============================================================================
const zephyr: FighterData = {
  id: 'zephyr',
  name: 'ZEPHYR',
  title: 'The Storm Dancer',
  weight: 78,
  walkSpeed: 1.15,
  runSpeed: 2.2,
  jumpForce: 17,
  doubleJumpForce: 15,
  airSpeed: 1.3,
  airAccel: 0.08,
  fallSpeed: 1.3,
  fastFallSpeed: 2.2,
  gravity: 0.09,
  shieldHealth: 50,
  colors: {
    primary: '#00E5FF',
    secondary: '#ECEFF1',
    accent: '#B0BEC5',
    glow: '#40C4FF',
  },
  size: { width: 36, height: 48 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 2,
      active: 2,
      endlag: 4,
      damage: 1.8,
      knockbackBase: 8,
      knockbackGrowth: 10,
      angle: 70,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 14, height: 10 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 2,
      active: 2,
      endlag: 4,
      damage: 1.8,
      knockbackBase: 8,
      knockbackGrowth: 10,
      angle: 60,
      hitboxes: [{ offsetX: 18, offsetY: -2, width: 14, height: 10 }],
    },
    jab3: {
      name: 'Gust Finisher',
      startup: 3,
      active: 3,
      endlag: 8,
      damage: 3.5,
      knockbackBase: 25,
      knockbackGrowth: 20,
      angle: 50,
      hitboxes: [{ offsetX: 18, offsetY: -4, width: 20, height: 16 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Wind Slash',
      startup: 5,
      active: 3,
      endlag: 8,
      damage: 6.5,
      knockbackBase: 15,
      knockbackGrowth: 35,
      angle: 40,
      hitboxes: [{ offsetX: 14, offsetY: -4, width: 24, height: 16 }],
    },
    up_tilt: {
      name: 'Breeze Kick',
      startup: 4,
      active: 4,
      endlag: 8,
      damage: 5.5,
      knockbackBase: 14,
      knockbackGrowth: 40,
      angle: 88,
      hitboxes: [{ offsetX: 2, offsetY: -22, width: 22, height: 20 }],
    },
    down_tilt: {
      name: 'Ankle Gust',
      startup: 3,
      active: 2,
      endlag: 6,
      damage: 5,
      knockbackBase: 10,
      knockbackGrowth: 25,
      angle: 75,
      hitboxes: [{ offsetX: 14, offsetY: 10, width: 20, height: 10 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Tempest Strike',
      startup: 14,
      active: 3,
      endlag: 22,
      damage: 14,
      knockbackBase: 32,
      knockbackGrowth: 78,
      angle: 38,
      hitboxes: [{ offsetX: 16, offsetY: -6, width: 30, height: 20 }],
    },
    up_smash: {
      name: 'Tornado Kick',
      startup: 10,
      active: 6,
      endlag: 20,
      damage: 12,
      knockbackBase: 28,
      knockbackGrowth: 72,
      angle: 85,
      hitboxes: [
        { offsetX: 0, offsetY: -20, width: 22, height: 24 },
        { offsetX: 0, offsetY: -34, width: 18, height: 14 },
      ],
    },
    down_smash: {
      name: 'Cyclone Sweep',
      startup: 8,
      active: 5,
      endlag: 18,
      damage: 11,
      knockbackBase: 28,
      knockbackGrowth: 68,
      angle: 22,
      hitboxes: [
        { offsetX: -20, offsetY: 6, width: 22, height: 14 },
        { offsetX: 18, offsetY: 6, width: 22, height: 14 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Wind Pirouette',
      startup: 3,
      active: 5,
      endlag: 7,
      damage: 6,
      knockbackBase: 12,
      knockbackGrowth: 30,
      angle: 55,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 30, height: 30 }],
    },
    forward_air: {
      name: 'Slicing Gale',
      startup: 5,
      active: 3,
      endlag: 8,
      damage: 7,
      knockbackBase: 14,
      knockbackGrowth: 38,
      angle: 42,
      hitboxes: [{ offsetX: 18, offsetY: -4, width: 20, height: 16 }],
    },
    back_air: {
      name: 'Tailwind Kick',
      startup: 6,
      active: 3,
      endlag: 10,
      damage: 10,
      knockbackBase: 24,
      knockbackGrowth: 72,
      angle: 145,
      hitboxes: [{ offsetX: -20, offsetY: -2, width: 18, height: 16 }],
    },
    up_air: {
      name: 'Sky Cutter',
      startup: 5,
      active: 4,
      endlag: 10,
      damage: 8.5,
      knockbackBase: 20,
      knockbackGrowth: 65,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -20, width: 24, height: 16 }],
    },
    down_air: {
      name: 'Downdraft',
      startup: 8,
      active: 3,
      endlag: 14,
      damage: 8,
      knockbackBase: 18,
      knockbackGrowth: 50,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 16, width: 18, height: 16 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Gale Strike',
      startup: 14,
      active: 40,
      endlag: 18,
      damage: 8,
      knockbackBase: 20,
      knockbackGrowth: 35,
      angle: 30,
      hitboxes: [{ offsetX: 28, offsetY: -2, width: 16, height: 14 }],
    },
    side_special: {
      name: 'Cyclone Dash',
      startup: 8,
      active: 10,
      endlag: 16,
      damage: 9,
      knockbackBase: 22,
      knockbackGrowth: 45,
      angle: 50,
      hitboxes: [{ offsetX: 10, offsetY: -2, width: 22, height: 22 }],
    },
    up_special: {
      name: 'Updraft',
      startup: 6,
      active: 14,
      endlag: 18,
      damage: 7,
      knockbackBase: 18,
      knockbackGrowth: 40,
      angle: 85,
      hitboxes: [{ offsetX: 0, offsetY: -14, width: 20, height: 28 }],
    },
    down_special: {
      name: 'Tailwind',
      startup: 10,
      active: 1,
      endlag: 14,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Grab',
      startup: 6,
      active: 2,
      endlag: 22,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 14, height: 12 }],
    },
    pummel: {
      name: 'Wind Pummel',
      startup: 1,
      active: 1,
      endlag: 5,
      damage: 1,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 8, offsetY: 0, width: 10, height: 10 }],
    },
    forward_throw: {
      name: 'Gust Push',
      startup: 6,
      active: 2,
      endlag: 12,
      damage: 6,
      knockbackBase: 35,
      knockbackGrowth: 40,
      angle: 45,
      hitboxes: [{ offsetX: 14, offsetY: 0, width: 12, height: 12 }],
    },
    back_throw: {
      name: 'Wind Reversal',
      startup: 7,
      active: 2,
      endlag: 14,
      damage: 7,
      knockbackBase: 40,
      knockbackGrowth: 50,
      angle: 140,
      hitboxes: [{ offsetX: -14, offsetY: 0, width: 12, height: 12 }],
    },
    up_throw: {
      name: 'Tornado Toss',
      startup: 6,
      active: 2,
      endlag: 16,
      damage: 5,
      knockbackBase: 45,
      knockbackGrowth: 45,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -12, width: 12, height: 12 }],
    },
    down_throw: {
      name: 'Slam Draft',
      startup: 5,
      active: 2,
      endlag: 10,
      damage: 4,
      knockbackBase: 20,
      knockbackGrowth: 20,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 12, height: 12 }],
    },
  },
};

// ============================================================================
// GRANITE - "The Living Fortress"
// Earth-themed super heavyweight. Incredibly strong, excellent shield game,
// very slow. Has super armor on some moves.
// ============================================================================
const granite: FighterData = {
  id: 'granite',
  name: 'GRANITE',
  title: 'The Living Fortress',
  weight: 120,
  walkSpeed: 0.7,
  runSpeed: 1.4,
  jumpForce: 14,
  doubleJumpForce: 12,
  airSpeed: 0.8,
  airAccel: 0.04,
  fallSpeed: 1.8,
  fastFallSpeed: 3.0,
  gravity: 0.12,
  shieldHealth: 50,
  colors: {
    primary: '#6D4C41',
    secondary: '#757575',
    accent: '#FFB300',
    glow: '#A1887F',
  },
  size: { width: 56, height: 58 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 5,
      active: 3,
      endlag: 8,
      damage: 3,
      knockbackBase: 12,
      knockbackGrowth: 18,
      angle: 65,
      hitboxes: [{ offsetX: 24, offsetY: -4, width: 22, height: 18 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 5,
      active: 3,
      endlag: 8,
      damage: 3.5,
      knockbackBase: 14,
      knockbackGrowth: 18,
      angle: 60,
      hitboxes: [{ offsetX: 26, offsetY: -2, width: 22, height: 18 }],
    },
    jab3: {
      name: 'Stone Slam',
      startup: 8,
      active: 4,
      endlag: 16,
      damage: 7,
      knockbackBase: 48,
      knockbackGrowth: 40,
      angle: 35,
      hitboxes: [{ offsetX: 26, offsetY: -4, width: 28, height: 22 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Rock Chop',
      startup: 9,
      active: 4,
      endlag: 16,
      damage: 11,
      knockbackBase: 30,
      knockbackGrowth: 65,
      angle: 38,
      hitboxes: [{ offsetX: 22, offsetY: -6, width: 32, height: 24 }],
    },
    up_tilt: {
      name: 'Pillar Jab',
      startup: 8,
      active: 5,
      endlag: 14,
      damage: 10,
      knockbackBase: 25,
      knockbackGrowth: 70,
      angle: 85,
      hitboxes: [{ offsetX: 4, offsetY: -30, width: 30, height: 26 }],
    },
    down_tilt: {
      name: 'Ground Crack',
      startup: 7,
      active: 4,
      endlag: 14,
      damage: 9,
      knockbackBase: 18,
      knockbackGrowth: 50,
      angle: 72,
      hitboxes: [{ offsetX: 20, offsetY: 12, width: 28, height: 14 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Seismic Crusher',
      startup: 22,
      active: 5,
      endlag: 32,
      damage: 24,
      knockbackBase: 50,
      knockbackGrowth: 100,
      angle: 32,
      hitboxes: [
        { offsetX: 24, offsetY: -8, width: 36, height: 28 },
        { offsetX: 42, offsetY: -4, width: 20, height: 20 },
      ],
    },
    up_smash: {
      name: 'Quake Pillar',
      startup: 16,
      active: 6,
      endlag: 28,
      damage: 20,
      knockbackBase: 42,
      knockbackGrowth: 92,
      angle: 86,
      hitboxes: [
        { offsetX: 0, offsetY: -26, width: 32, height: 30 },
        { offsetX: 0, offsetY: -42, width: 24, height: 18 },
      ],
    },
    down_smash: {
      name: 'Fault Line',
      startup: 18,
      active: 8,
      endlag: 26,
      damage: 18,
      knockbackBase: 42,
      knockbackGrowth: 88,
      angle: 20,
      hitboxes: [
        { offsetX: -30, offsetY: 8, width: 32, height: 18 },
        { offsetX: 28, offsetY: 8, width: 32, height: 18 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Stone Body',
      startup: 8,
      active: 6,
      endlag: 16,
      damage: 10,
      knockbackBase: 22,
      knockbackGrowth: 50,
      angle: 50,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 42, height: 42 }],
    },
    forward_air: {
      name: 'Rock Hammer',
      startup: 12,
      active: 4,
      endlag: 20,
      damage: 14,
      knockbackBase: 28,
      knockbackGrowth: 72,
      angle: 35,
      hitboxes: [{ offsetX: 24, offsetY: -4, width: 26, height: 22 }],
    },
    back_air: {
      name: 'Boulder Kick',
      startup: 10,
      active: 4,
      endlag: 18,
      damage: 13,
      knockbackBase: 26,
      knockbackGrowth: 68,
      angle: 145,
      hitboxes: [{ offsetX: -26, offsetY: -2, width: 24, height: 20 }],
    },
    up_air: {
      name: 'Stone Headbutt',
      startup: 9,
      active: 4,
      endlag: 16,
      damage: 12,
      knockbackBase: 24,
      knockbackGrowth: 65,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -26, width: 30, height: 20 }],
    },
    down_air: {
      name: 'Meteor Drop',
      startup: 16,
      active: 4,
      endlag: 24,
      damage: 16,
      knockbackBase: 30,
      knockbackGrowth: 80,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 22, width: 26, height: 22 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Boulder Bash',
      startup: 20,
      active: 50,
      endlag: 22,
      damage: 15,
      knockbackBase: 35,
      knockbackGrowth: 70,
      angle: 35,
      hitboxes: [{ offsetX: 32, offsetY: -4, width: 22, height: 22 }],
    },
    side_special: {
      name: 'Tectonic Slide',
      startup: 10,
      active: 18,
      endlag: 24,
      damage: 13,
      knockbackBase: 35,
      knockbackGrowth: 60,
      angle: 30,
      hitboxes: [{ offsetX: 16, offsetY: 0, width: 34, height: 30 }],
    },
    up_special: {
      name: 'Pillar Rise',
      startup: 10,
      active: 10,
      endlag: 26,
      damage: 12,
      knockbackBase: 25,
      knockbackGrowth: 55,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: -18, width: 28, height: 34 }],
    },
    down_special: {
      name: 'Earthen Wall',
      startup: 12,
      active: 60,
      endlag: 16,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 24, offsetY: 0, width: 12, height: 48 }],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Grab',
      startup: 7,
      active: 2,
      endlag: 24,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 22, offsetY: -2, width: 18, height: 16 }],
    },
    pummel: {
      name: 'Crush Pummel',
      startup: 1,
      active: 1,
      endlag: 10,
      damage: 2,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 12, offsetY: 0, width: 12, height: 12 }],
    },
    forward_throw: {
      name: 'Stone Hurl',
      startup: 10,
      active: 2,
      endlag: 20,
      damage: 11,
      knockbackBase: 52,
      knockbackGrowth: 60,
      angle: 38,
      hitboxes: [{ offsetX: 18, offsetY: 0, width: 16, height: 16 }],
    },
    back_throw: {
      name: 'Rubble Toss',
      startup: 10,
      active: 2,
      endlag: 20,
      damage: 12,
      knockbackBase: 55,
      knockbackGrowth: 65,
      angle: 140,
      hitboxes: [{ offsetX: -18, offsetY: 0, width: 16, height: 16 }],
    },
    up_throw: {
      name: 'Catapult',
      startup: 10,
      active: 2,
      endlag: 22,
      damage: 10,
      knockbackBase: 60,
      knockbackGrowth: 60,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -16, width: 16, height: 16 }],
    },
    down_throw: {
      name: 'Bury Slam',
      startup: 8,
      active: 3,
      endlag: 18,
      damage: 8,
      knockbackBase: 25,
      knockbackGrowth: 30,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: 10, width: 16, height: 16 }],
    },
  },
};

// ============================================================================
// VOLT - "The Living Circuit"
// Electric-themed glass cannon. Extreme speed and damage output, very easy to
// KO. Fast attacks with electric stun effect (slightly more hitstun).
// ============================================================================
const volt: FighterData = {
  id: 'volt',
  name: 'VOLT',
  title: 'The Living Circuit',
  weight: 82,
  walkSpeed: 1.1,
  runSpeed: 2.1,
  jumpForce: 16.5,
  doubleJumpForce: 14.5,
  airSpeed: 1.2,
  airAccel: 0.07,
  fallSpeed: 1.4,
  fastFallSpeed: 2.4,
  gravity: 0.095,
  shieldHealth: 50,
  colors: {
    primary: '#FFD600',
    secondary: '#2979FF',
    accent: '#FFFFFF',
    glow: '#FFEA00',
  },
  size: { width: 38, height: 46 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 2,
      active: 2,
      endlag: 5,
      damage: 2,
      knockbackBase: 10,
      knockbackGrowth: 12,
      angle: 70,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 14, height: 10 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 2,
      active: 2,
      endlag: 5,
      damage: 2,
      knockbackBase: 10,
      knockbackGrowth: 12,
      angle: 65,
      hitboxes: [{ offsetX: 18, offsetY: -2, width: 14, height: 10 }],
    },
    jab3: {
      name: 'Spark Burst',
      startup: 3,
      active: 3,
      endlag: 10,
      damage: 4.5,
      knockbackBase: 30,
      knockbackGrowth: 28,
      angle: 45,
      hitboxes: [{ offsetX: 18, offsetY: -4, width: 22, height: 16 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Arc Zap',
      startup: 5,
      active: 3,
      endlag: 9,
      damage: 8,
      knockbackBase: 18,
      knockbackGrowth: 45,
      angle: 38,
      hitboxes: [{ offsetX: 16, offsetY: -4, width: 24, height: 16 }],
    },
    up_tilt: {
      name: 'Static Spark',
      startup: 4,
      active: 4,
      endlag: 9,
      damage: 7,
      knockbackBase: 16,
      knockbackGrowth: 48,
      angle: 86,
      hitboxes: [{ offsetX: 2, offsetY: -22, width: 24, height: 20 }],
    },
    down_tilt: {
      name: 'Ground Wire',
      startup: 4,
      active: 2,
      endlag: 7,
      damage: 6,
      knockbackBase: 12,
      knockbackGrowth: 30,
      angle: 75,
      hitboxes: [{ offsetX: 14, offsetY: 10, width: 22, height: 10 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Thunderbolt',
      startup: 14,
      active: 3,
      endlag: 22,
      damage: 16,
      knockbackBase: 35,
      knockbackGrowth: 82,
      angle: 36,
      hitboxes: [
        { offsetX: 18, offsetY: -6, width: 28, height: 20 },
        { offsetX: 34, offsetY: -2, width: 14, height: 14 },
      ],
    },
    up_smash: {
      name: 'Lightning Rod',
      startup: 10,
      active: 5,
      endlag: 20,
      damage: 14,
      knockbackBase: 30,
      knockbackGrowth: 78,
      angle: 88,
      hitboxes: [
        { offsetX: 0, offsetY: -22, width: 20, height: 26 },
        { offsetX: 0, offsetY: -36, width: 16, height: 14 },
      ],
    },
    down_smash: {
      name: 'Tesla Slam',
      startup: 12,
      active: 4,
      endlag: 20,
      damage: 15,
      knockbackBase: 38,
      knockbackGrowth: 85,
      angle: 22,
      hitboxes: [
        { offsetX: -22, offsetY: 6, width: 24, height: 16 },
        { offsetX: 20, offsetY: 6, width: 24, height: 16 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Discharge',
      startup: 4,
      active: 4,
      endlag: 9,
      damage: 7,
      knockbackBase: 14,
      knockbackGrowth: 35,
      angle: 55,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 32, height: 32 }],
    },
    forward_air: {
      name: 'Electric Kick',
      startup: 7,
      active: 3,
      endlag: 12,
      damage: 12,
      knockbackBase: 24,
      knockbackGrowth: 75,
      angle: 270,
      hitboxes: [{ offsetX: 20, offsetY: 2, width: 20, height: 16 }],
    },
    back_air: {
      name: 'Shock Heel',
      startup: 6,
      active: 3,
      endlag: 12,
      damage: 10,
      knockbackBase: 22,
      knockbackGrowth: 62,
      angle: 145,
      hitboxes: [{ offsetX: -20, offsetY: -2, width: 18, height: 16 }],
    },
    up_air: {
      name: 'Spark Rise',
      startup: 5,
      active: 4,
      endlag: 10,
      damage: 8,
      knockbackBase: 16,
      knockbackGrowth: 52,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -20, width: 22, height: 16 }],
    },
    down_air: {
      name: 'Thunder Spike',
      startup: 10,
      active: 3,
      endlag: 18,
      damage: 11,
      knockbackBase: 22,
      knockbackGrowth: 65,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 18, width: 18, height: 18 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Spark Shot',
      startup: 8,
      active: 30,
      endlag: 14,
      damage: 7,
      knockbackBase: 15,
      knockbackGrowth: 30,
      angle: 25,
      hitboxes: [{ offsetX: 24, offsetY: -2, width: 12, height: 10 }],
    },
    side_special: {
      name: 'Lightning Dash',
      startup: 4,
      active: 6,
      endlag: 18,
      damage: 10,
      knockbackBase: 25,
      knockbackGrowth: 55,
      angle: 40,
      hitboxes: [{ offsetX: 12, offsetY: -2, width: 20, height: 18 }],
    },
    up_special: {
      name: 'Tesla Coil',
      startup: 6,
      active: 12,
      endlag: 20,
      damage: 11,
      knockbackBase: 28,
      knockbackGrowth: 65,
      angle: 78,
      hitboxes: [{ offsetX: 0, offsetY: -16, width: 22, height: 30 }],
    },
    down_special: {
      name: 'Static Field',
      startup: 16,
      active: 120,
      endlag: 14,
      damage: 6,
      knockbackBase: 20,
      knockbackGrowth: 25,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 24, height: 12 }],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Grab',
      startup: 6,
      active: 2,
      endlag: 22,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 14, height: 12 }],
    },
    pummel: {
      name: 'Shock Pummel',
      startup: 1,
      active: 1,
      endlag: 6,
      damage: 1.2,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 8, offsetY: 0, width: 10, height: 10 }],
    },
    forward_throw: {
      name: 'Volt Toss',
      startup: 6,
      active: 2,
      endlag: 14,
      damage: 7,
      knockbackBase: 38,
      knockbackGrowth: 48,
      angle: 42,
      hitboxes: [{ offsetX: 14, offsetY: 0, width: 12, height: 12 }],
    },
    back_throw: {
      name: 'Reverse Charge',
      startup: 7,
      active: 2,
      endlag: 16,
      damage: 8,
      knockbackBase: 42,
      knockbackGrowth: 55,
      angle: 140,
      hitboxes: [{ offsetX: -14, offsetY: 0, width: 12, height: 12 }],
    },
    up_throw: {
      name: 'Overcharge',
      startup: 6,
      active: 2,
      endlag: 18,
      damage: 6,
      knockbackBase: 50,
      knockbackGrowth: 50,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -12, width: 12, height: 12 }],
    },
    down_throw: {
      name: 'Circuit Slam',
      startup: 5,
      active: 2,
      endlag: 12,
      damage: 5,
      knockbackBase: 25,
      knockbackGrowth: 25,
      angle: 75,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 12, height: 12 }],
    },
  },
};

// ============================================================================
// TIDE - "The Depth Caller"
// Water-themed grappler. Best grab game, can combo out of grabs, good edge
// guarding. Longer grab range, multiple throw options, command grab special.
// ============================================================================
const tide: FighterData = {
  id: 'tide',
  name: 'TIDE',
  title: 'The Depth Caller',
  weight: 98,
  walkSpeed: 0.9,
  runSpeed: 1.6,
  jumpForce: 15.5,
  doubleJumpForce: 13.5,
  airSpeed: 0.95,
  airAccel: 0.055,
  fallSpeed: 1.45,
  fastFallSpeed: 2.5,
  gravity: 0.098,
  shieldHealth: 50,
  colors: {
    primary: '#0D47A1',
    secondary: '#00897B',
    accent: '#00E5FF',
    glow: '#29B6F6',
  },
  size: { width: 48, height: 54 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 4,
      active: 2,
      endlag: 6,
      damage: 2.5,
      knockbackBase: 10,
      knockbackGrowth: 14,
      angle: 68,
      hitboxes: [{ offsetX: 20, offsetY: -4, width: 18, height: 14 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 4,
      active: 2,
      endlag: 6,
      damage: 2.5,
      knockbackBase: 12,
      knockbackGrowth: 14,
      angle: 62,
      hitboxes: [{ offsetX: 22, offsetY: -2, width: 18, height: 14 }],
    },
    jab3: {
      name: 'Splash Strike',
      startup: 5,
      active: 3,
      endlag: 12,
      damage: 5,
      knockbackBase: 35,
      knockbackGrowth: 32,
      angle: 42,
      hitboxes: [{ offsetX: 22, offsetY: -4, width: 24, height: 18 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Wave Slap',
      startup: 7,
      active: 4,
      endlag: 12,
      damage: 8.5,
      knockbackBase: 22,
      knockbackGrowth: 50,
      angle: 36,
      hitboxes: [{ offsetX: 18, offsetY: -4, width: 28, height: 20 }],
    },
    up_tilt: {
      name: 'Spout',
      startup: 6,
      active: 5,
      endlag: 12,
      damage: 7.5,
      knockbackBase: 18,
      knockbackGrowth: 52,
      angle: 86,
      hitboxes: [{ offsetX: 4, offsetY: -26, width: 26, height: 22 }],
    },
    down_tilt: {
      name: 'Low Tide',
      startup: 5,
      active: 3,
      endlag: 10,
      damage: 7,
      knockbackBase: 14,
      knockbackGrowth: 35,
      angle: 72,
      hitboxes: [{ offsetX: 16, offsetY: 10, width: 26, height: 12 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Wave Crash',
      startup: 16,
      active: 5,
      endlag: 24,
      damage: 17,
      knockbackBase: 38,
      knockbackGrowth: 90,
      angle: 34,
      hitboxes: [
        { offsetX: 20, offsetY: -8, width: 32, height: 24 },
        { offsetX: 36, offsetY: -2, width: 18, height: 18 },
      ],
    },
    up_smash: {
      name: 'Tidal Spout',
      startup: 12,
      active: 5,
      endlag: 22,
      damage: 15,
      knockbackBase: 32,
      knockbackGrowth: 82,
      angle: 86,
      hitboxes: [
        { offsetX: 0, offsetY: -24, width: 26, height: 26 },
        { offsetX: 0, offsetY: -38, width: 20, height: 16 },
      ],
    },
    down_smash: {
      name: 'Flood Burst',
      startup: 14,
      active: 6,
      endlag: 22,
      damage: 14,
      knockbackBase: 34,
      knockbackGrowth: 78,
      angle: 24,
      hitboxes: [
        { offsetX: -26, offsetY: 6, width: 28, height: 16 },
        { offsetX: 24, offsetY: 6, width: 28, height: 16 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Aqua Ring',
      startup: 6,
      active: 5,
      endlag: 12,
      damage: 8,
      knockbackBase: 16,
      knockbackGrowth: 38,
      angle: 52,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 36, height: 36 }],
    },
    forward_air: {
      name: 'Trident Thrust',
      startup: 8,
      active: 3,
      endlag: 14,
      damage: 10,
      knockbackBase: 22,
      knockbackGrowth: 55,
      angle: 40,
      hitboxes: [{ offsetX: 22, offsetY: -4, width: 22, height: 16 }],
    },
    back_air: {
      name: 'Riptide Kick',
      startup: 7,
      active: 3,
      endlag: 14,
      damage: 11,
      knockbackBase: 24,
      knockbackGrowth: 65,
      angle: 145,
      hitboxes: [{ offsetX: -22, offsetY: -2, width: 20, height: 16 }],
    },
    up_air: {
      name: 'Bubble Pop',
      startup: 6,
      active: 4,
      endlag: 12,
      damage: 8.5,
      knockbackBase: 18,
      knockbackGrowth: 55,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -22, width: 26, height: 16 }],
    },
    down_air: {
      name: 'Depth Charge',
      startup: 12,
      active: 3,
      endlag: 18,
      damage: 13,
      knockbackBase: 28,
      knockbackGrowth: 78,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 20, width: 22, height: 20 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Hydro Cannon',
      startup: 16,
      active: 35,
      endlag: 20,
      damage: 5,
      knockbackBase: 40,
      knockbackGrowth: 20,
      angle: 25,
      hitboxes: [{ offsetX: 28, offsetY: -2, width: 18, height: 14 }],
    },
    side_special: {
      name: 'Riptide',
      startup: 10,
      active: 6,
      endlag: 22,
      damage: 12,
      knockbackBase: 30,
      knockbackGrowth: 55,
      angle: 35,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 24, height: 20 }],
    },
    up_special: {
      name: 'Geyser',
      startup: 8,
      active: 14,
      endlag: 20,
      damage: 9,
      knockbackBase: 22,
      knockbackGrowth: 50,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -16, width: 24, height: 32 }],
    },
    down_special: {
      name: 'Whirlpool',
      startup: 14,
      active: 90,
      endlag: 18,
      damage: 3,
      knockbackBase: 5,
      knockbackGrowth: 10,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: 4, width: 40, height: 20 }],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Tentacle Grab',
      startup: 6,
      active: 3,
      endlag: 20,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 18, offsetY: -2, width: 22, height: 16 }],
    },
    pummel: {
      name: 'Crush Pummel',
      startup: 1,
      active: 1,
      endlag: 7,
      damage: 1.5,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 10, offsetY: 0, width: 10, height: 10 }],
    },
    forward_throw: {
      name: 'Current Push',
      startup: 8,
      active: 2,
      endlag: 16,
      damage: 8,
      knockbackBase: 42,
      knockbackGrowth: 52,
      angle: 42,
      hitboxes: [{ offsetX: 16, offsetY: 0, width: 14, height: 14 }],
    },
    back_throw: {
      name: 'Undertow',
      startup: 10,
      active: 3,
      endlag: 18,
      damage: 12,
      knockbackBase: 60,
      knockbackGrowth: 78,
      angle: 140,
      hitboxes: [{ offsetX: -16, offsetY: 0, width: 14, height: 14 }],
    },
    up_throw: {
      name: 'Waterspout',
      startup: 8,
      active: 2,
      endlag: 18,
      damage: 7,
      knockbackBase: 50,
      knockbackGrowth: 52,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -14, width: 14, height: 14 }],
    },
    down_throw: {
      name: 'Anchor Drop',
      startup: 6,
      active: 2,
      endlag: 14,
      damage: 6,
      knockbackBase: 28,
      knockbackGrowth: 30,
      angle: 72,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 14, height: 14 }],
    },
  },
};

// ============================================================================
// NOVA - "The Cosmic Wanderer"
// Space-themed all-rounder. Balanced stats, good at everything but master of
// nothing. Well-rounded moveset, versatile, rewards adaptation.
// ============================================================================
const nova: FighterData = {
  id: 'nova',
  name: 'NOVA',
  title: 'The Cosmic Wanderer',
  weight: 95,
  walkSpeed: 1.0,
  runSpeed: 1.85,
  jumpForce: 16,
  doubleJumpForce: 14,
  airSpeed: 1.05,
  airAccel: 0.06,
  fallSpeed: 1.45,
  fastFallSpeed: 2.5,
  gravity: 0.098,
  shieldHealth: 50,
  colors: {
    primary: '#7B1FA2',
    secondary: '#E91E90',
    accent: '#F5F5F5',
    glow: '#CE93D8',
  },
  size: { width: 42, height: 50 },
  moves: {
    // -- Jab (3-hit combo) --
    jab1: {
      name: 'Jab 1',
      startup: 3,
      active: 2,
      endlag: 5,
      damage: 2.2,
      knockbackBase: 10,
      knockbackGrowth: 12,
      angle: 68,
      hitboxes: [{ offsetX: 18, offsetY: -4, width: 16, height: 12 }],
    },
    jab2: {
      name: 'Jab 2',
      startup: 3,
      active: 2,
      endlag: 6,
      damage: 2.2,
      knockbackBase: 10,
      knockbackGrowth: 14,
      angle: 62,
      hitboxes: [{ offsetX: 20, offsetY: -2, width: 16, height: 12 }],
    },
    jab3: {
      name: 'Nova Burst',
      startup: 4,
      active: 3,
      endlag: 10,
      damage: 4.5,
      knockbackBase: 32,
      knockbackGrowth: 28,
      angle: 45,
      hitboxes: [{ offsetX: 20, offsetY: -4, width: 22, height: 16 }],
    },

    // -- Tilts --
    forward_tilt: {
      name: 'Star Sweep',
      startup: 6,
      active: 3,
      endlag: 10,
      damage: 8,
      knockbackBase: 20,
      knockbackGrowth: 48,
      angle: 38,
      hitboxes: [{ offsetX: 16, offsetY: -4, width: 26, height: 18 }],
    },
    up_tilt: {
      name: 'Cosmic Arc',
      startup: 5,
      active: 4,
      endlag: 10,
      damage: 7,
      knockbackBase: 18,
      knockbackGrowth: 52,
      angle: 86,
      hitboxes: [{ offsetX: 2, offsetY: -24, width: 24, height: 22 }],
    },
    down_tilt: {
      name: 'Nebula Slide',
      startup: 5,
      active: 3,
      endlag: 8,
      damage: 6.5,
      knockbackBase: 14,
      knockbackGrowth: 32,
      angle: 72,
      hitboxes: [{ offsetX: 14, offsetY: 10, width: 24, height: 10 }],
    },

    // -- Smash Attacks --
    forward_smash: {
      name: 'Supernova Punch',
      startup: 14,
      active: 4,
      endlag: 22,
      damage: 16,
      knockbackBase: 36,
      knockbackGrowth: 88,
      angle: 36,
      hitboxes: [
        { offsetX: 18, offsetY: -6, width: 30, height: 22 },
        { offsetX: 34, offsetY: -2, width: 16, height: 16 },
      ],
    },
    up_smash: {
      name: 'Constellation Rise',
      startup: 11,
      active: 5,
      endlag: 20,
      damage: 14,
      knockbackBase: 32,
      knockbackGrowth: 82,
      angle: 86,
      hitboxes: [
        { offsetX: 0, offsetY: -22, width: 24, height: 26 },
        { offsetX: 0, offsetY: -36, width: 18, height: 14 },
      ],
    },
    down_smash: {
      name: 'Singularity',
      startup: 12,
      active: 5,
      endlag: 20,
      damage: 13,
      knockbackBase: 32,
      knockbackGrowth: 78,
      angle: 24,
      hitboxes: [
        { offsetX: -24, offsetY: 6, width: 24, height: 16 },
        { offsetX: 22, offsetY: 6, width: 24, height: 16 },
      ],
    },

    // -- Aerials --
    neutral_air: {
      name: 'Orbital Ring',
      startup: 5,
      active: 5,
      endlag: 10,
      damage: 7.5,
      knockbackBase: 16,
      knockbackGrowth: 36,
      angle: 52,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 34, height: 34 }],
    },
    forward_air: {
      name: 'Shooting Star',
      startup: 7,
      active: 3,
      endlag: 12,
      damage: 10.5,
      knockbackBase: 22,
      knockbackGrowth: 68,
      angle: 38,
      hitboxes: [{ offsetX: 20, offsetY: -4, width: 22, height: 16 }],
    },
    back_air: {
      name: 'Comet Tail',
      startup: 7,
      active: 3,
      endlag: 12,
      damage: 11.5,
      knockbackBase: 26,
      knockbackGrowth: 74,
      angle: 145,
      hitboxes: [{ offsetX: -22, offsetY: -2, width: 20, height: 16 }],
    },
    up_air: {
      name: 'Stardust',
      startup: 6,
      active: 4,
      endlag: 11,
      damage: 8.5,
      knockbackBase: 18,
      knockbackGrowth: 58,
      angle: 82,
      hitboxes: [{ offsetX: 0, offsetY: -22, width: 26, height: 16 }],
    },
    down_air: {
      name: 'Asteroid Drop',
      startup: 11,
      active: 3,
      endlag: 16,
      damage: 11,
      knockbackBase: 24,
      knockbackGrowth: 68,
      angle: 270,
      hitboxes: [{ offsetX: 0, offsetY: 18, width: 20, height: 18 }],
    },

    // -- Specials --
    neutral_special: {
      name: 'Star Shot',
      startup: 12,
      active: 35,
      endlag: 16,
      damage: 3,
      knockbackBase: 10,
      knockbackGrowth: 15,
      angle: 35,
      hitboxes: [
        { offsetX: 24, offsetY: -4, width: 14, height: 12 },
        { offsetX: 24, offsetY: 0, width: 14, height: 12 },
        { offsetX: 24, offsetY: 4, width: 14, height: 12 },
      ],
    },
    side_special: {
      name: 'Warp Strike',
      startup: 6,
      active: 4,
      endlag: 16,
      damage: 10,
      knockbackBase: 24,
      knockbackGrowth: 55,
      angle: 42,
      hitboxes: [{ offsetX: 14, offsetY: -2, width: 20, height: 18 }],
    },
    up_special: {
      name: 'Comet Rise',
      startup: 7,
      active: 10,
      endlag: 18,
      damage: 9,
      knockbackBase: 22,
      knockbackGrowth: 52,
      angle: 70,
      hitboxes: [{ offsetX: 8, offsetY: -14, width: 22, height: 26 }],
    },
    down_special: {
      name: 'Gravity Well',
      startup: 14,
      active: 80,
      endlag: 16,
      damage: 4,
      knockbackBase: 8,
      knockbackGrowth: 12,
      angle: 80,
      hitboxes: [{ offsetX: 0, offsetY: 0, width: 44, height: 44 }],
    },

    // -- Grab / Throws --
    grab: {
      name: 'Grab',
      startup: 6,
      active: 2,
      endlag: 20,
      damage: 0,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 16, offsetY: -2, width: 16, height: 14 }],
    },
    pummel: {
      name: 'Cosmic Pummel',
      startup: 1,
      active: 1,
      endlag: 7,
      damage: 1.3,
      knockbackBase: 0,
      knockbackGrowth: 0,
      angle: 0,
      hitboxes: [{ offsetX: 8, offsetY: 0, width: 10, height: 10 }],
    },
    forward_throw: {
      name: 'Star Toss',
      startup: 7,
      active: 2,
      endlag: 14,
      damage: 8,
      knockbackBase: 40,
      knockbackGrowth: 50,
      angle: 42,
      hitboxes: [{ offsetX: 14, offsetY: 0, width: 14, height: 14 }],
    },
    back_throw: {
      name: 'Void Fling',
      startup: 8,
      active: 2,
      endlag: 16,
      damage: 9,
      knockbackBase: 48,
      knockbackGrowth: 58,
      angle: 140,
      hitboxes: [{ offsetX: -14, offsetY: 0, width: 14, height: 14 }],
    },
    up_throw: {
      name: 'Launch to Orbit',
      startup: 7,
      active: 2,
      endlag: 18,
      damage: 7,
      knockbackBase: 52,
      knockbackGrowth: 52,
      angle: 90,
      hitboxes: [{ offsetX: 0, offsetY: -14, width: 14, height: 14 }],
    },
    down_throw: {
      name: 'Gravity Crush',
      startup: 6,
      active: 2,
      endlag: 14,
      damage: 6,
      knockbackBase: 28,
      knockbackGrowth: 30,
      angle: 72,
      hitboxes: [{ offsetX: 0, offsetY: 8, width: 14, height: 14 }],
    },
  },
};

// ============================================================================
// Exports
// ============================================================================

export const CHARACTERS: Record<string, FighterData> = {
  blaze,
  zephyr,
  granite,
  volt,
  tide,
  nova,
};

export const CHARACTER_LIST: string[] = [
  'blaze',
  'zephyr',
  'granite',
  'volt',
  'tide',
  'nova',
];
